
package jaxwsSample1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AppWS", targetNamespace = "http://jaxwsSample1/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AppWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://jaxwsSample1/", className = "jaxwsSample1.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://jaxwsSample1/", className = "jaxwsSample1.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
