package jaxwsSample1;

/**
 * A Simple Web Service Client generated by Maven archetype (mycompany-archetype-j2ee1.5-jaxws)
 *
 * @author RANGINY1
 */

public class AppWSClient{

   public static void main(String[] args) {
        AppWSService service = new AppWSService();
        AppWS port = service.getAppWSPort();
        System.out.println(port.sayHello("WHIC WS Client ! Thank you for accessing AppWSService."));
    }

   public boolean accessWebService(){
       boolean accesStatus = false;
       AppWSService service = new AppWSService();
        AppWS port = service.getAppWSPort();
        port.sayHello(" Testing Web Service");
        accesStatus=true;
        return accesStatus;
   }
}
