package jaxwssample1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Thu Jun 02 14:00:14 MSD 2011
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "http://jaxwsSample1/", name = "AppWS")
@XmlSeeAlso({ObjectFactory.class})
public interface AppWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://jaxwsSample1/", className = "jaxwssample1.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://jaxwsSample1/", className = "jaxwssample1.SayHelloResponse")
    @WebMethod
    public java.lang.String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
