package jaxwsSample1;

import javax.jws.WebService;

/**
 * A Simple Web Service generated by Maven archetype (mycompany-archetype-j2ee1.5-jaxws)
 *
 * @author RANGINY1
 */
@WebService
public class AppWS {

    public String sayHello(String param) {     
        return "Hello " + param;
    }
}


