
package jaxwsSample1;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AppWSService", targetNamespace = "http://jaxwsSample1/", wsdlLocation = "file:/C:/XInnovation/menta/jaxwsSample1/jaxwsSample1Client/target/AppWSService.wsdl")
public class AppWSService
    extends Service
{

    private final static URL APPWSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(jaxwsSample1.AppWSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = jaxwsSample1.AppWSService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/XInnovation/menta/jaxwsSample1/jaxwsSample1Client/target/AppWSService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/XInnovation/menta/jaxwsSample1/jaxwsSample1Client/target/AppWSService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        APPWSSERVICE_WSDL_LOCATION = url;
    }

    public AppWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AppWSService() {
        super(APPWSSERVICE_WSDL_LOCATION, new QName("http://jaxwsSample1/", "AppWSService"));
    }

    /**
     * 
     * @return
     *     returns AppWS
     */
    @WebEndpoint(name = "AppWSPort")
    public AppWS getAppWSPort() {
        return super.getPort(new QName("http://jaxwsSample1/", "AppWSPort"), AppWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AppWS
     */
    @WebEndpoint(name = "AppWSPort")
    public AppWS getAppWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jaxwsSample1/", "AppWSPort"), AppWS.class, features);
    }

}
